(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1400,
	height: 800,
	fps: 40,
	color: "#ED0077",
	manifest: []
};



// symbols:



(lib.m_word2 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKBOQgFgEgCgBIgEgEIAEgDQASgNAMgbIgKAAQgPAdgZARIgDACIgCgDIgGgGIgGgEIAGgDQASgKAOgWIgIAAQgKALgMAJIgDACIgDgDIgLgLIgaANIgEACIgIgTIAEgBIAVgKIAAgtIgUAAIAAgTIAUAAIAAgjIASAAIAAAjIAUAAIAAATIgUAAIAAAlIAQgHIgIAAIAAgQIBwAAIAAAQIhIAAIgCAEIBGAAIAAAKQgEAvgIAJQgEAEgJABIgGAAIgOAAIAAgEQAAgEgDgEIgBgBQgGAHgIAGIgDACgAAnAWQgMAggWAPQAFADADAEQAXgRAMglIAPAAQgEAlgEAGQgCABgEAAIgPgBQADAGAAAEIAKAAIAGAAQAHAAADgEQAHgIAEguIAAgFIhKAAQAFgGADgGIBGAAIAAgIIhoAAIAAAIIAZAAQgNAWgWANIAIAHQAMgIALgMIAQAAQgOAagXANQAFAEACAEQAYgQAQgfgAAgA9IACAAIAPABIADAAQADgEADggIgHAAQgHAUgMAPgAhIgeIAUAAIAAA0IgYAKIAFALIAygYIgDgKIgSAIIAAgvIAUAAIAAgLIgUAAIAAgjIgKAAIAAAjIgUAAgAgSAPQAHgHACgEIgMAAgAgNgOIAAg/IBTAAIAAA/gAgJgSIBLAAIAAg3IhLAAgAAAgaIAAgPIA4AAIAAAPgAADgeIAxAAIAAgHIgxAAgAAAgxIAAgPIA4AAIAAAPgAADg1IAxAAIAAgHIgxAAg");
	this.shape.setTransform(214.8,0.4,5.044,5.044);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhFBKIgKgJIgFgEIAGgDQA0gbAQhHIABgDIAEAAIABAAIgCgNIgqAAIAAgTIA7AAIAAAEQAABXBFApIAFADIgFAEQgCABgFAHIgCAEIgDgDQgygdgRg2QgTA6guAbIgDABgAhNA+QAGADAFAGQAygeARhBQAPA+A2AgQACgFAGgFQhGgqAAhZIg0AAIAAALIArAAIABAWIgGgBQgRBJg2Acg");
	this.shape_1.setTransform(129.4,2.4,5.044,5.044);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhBBOIgHgIIgFgEIAGgCQAZgMAUgRQAVgRAJgTIACgDIASAFIgDADQgJARgMAOQASAQAGAIIACADIgOANIgDgEQgIgJgNgOQgWATgaANIgEACgAhFBDIAHAJQAbgNAXgVQAQARAJAKIAIgIQgHgHgTgTQAMgOALgSIgLgDQgXAsg1AXgAAkBQIgBgDQAAgEgDgFIgDgHIAeABIAAiLIATAAIAACKQAAANgKAEQgHACgWAAgAAnBMQAXABAFgCQAHgDAAgLIAAiHIgLAAIAACHQAAAFgEAAIgXAAgAhBAoIgGgIIgFgEIAGgDQAWgJASgRQgcABgCABIgFACIgBgEIgDgKIgCgEIAFgBQACAAAFgFIAPgTIgeAAIAAgSIAqAAQgEgJgDgFIgDgEIAFgBIAKgEIADAAIACACQAGAJAFAMIAiAAIAAASIgsAAIgRAWIAYgBIAJgOIABgEIAQAHIgCAEQgVAqgwAaIgEACgAhEAdIAHAKQAugaAWgpIgJgDIgKAQIgkACQAMgMANgTIAqAAIAAgLIgiAAIABAAQgEgMgIgJIgKACQAGAIAEALIgsAAIAAALIAiAAQgLAQgJAJQgFAGgEABIADAKIAqgDQgUAVgcANgAAcAoIAAhkIATAAIAABkgAAgAkIALAAIAAhcIgLAAg");
	this.shape_2.setTransform(42.5,-0.5,5.044,5.044);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMBNIAAiYIBAAAIAABkQAAAMgJAEQgEABgQAAIgKAAIAAgCQgBgGgCgEIgCgFIAAA0gAAQBJIAMAAIAAiFIAgAAIAABVQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgUAAQACADACAIIAGAAQAPgBAEgBQAGgDAAgJIAAhgIg4AAgAAgAXIAGABIASAAIAAhQIgYAAgAhEBEIgEgKIgDgEIAEgCQAFgCAAgFIAAh4IBGAAIAABVIgyAAIAAAhIAYgIIgIgNIAAAAIgCgEIAQgIIACADQAPAZAHATIABADIgDACIgMAHIgIgSQgsAQgEADIgEAEgAg+AtQAAAHgHAEQADADACAIQAEgDAwgRIAIARIAIgGQgEgOgRgdIgKAFIAKASIghALIAAgsIAyAAIAAhNIg+AAgAgygCIAAgaIApAAIAAAagAgugGIAhAAIAAgRIghAAgAgygmIAAgXIApAAIAAAXgAgugpIAhAAIAAgQIghAAg");
	this.shape_3.setTransform(-43,1.8,5.044,5.044);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhHBOIgGgGIgEgDIADgDQAKgOAAgdIAAgsIA8AAIAAAAIgEgJQgxAEgEACIgDABIgGgPIgBgEIAEgBQACAAAFgGQANgPAJgPIABgDIAUAHIgIAKIABAAIAMgEIACACQAKANAIASIAAgtIATAAIAAAYIAuAAIAAASIguAAIAAARIAAADIADABIAtgBIAFgBIACASIgDABIgQABIgkAAIAAAQIAwAAIAAATIgHAAIgpAAIAAAXIAAABQABABAFAAIAdAAQABAAABAAQAAAAABAAQAAAAABgBQAAAAAAgBQABgDABgNIAAgHIAGAEIAMAEIAAAEQgBASgEAGQgFAIgNgBIgfAAQgMAAgGgDQgGgFAAgMIAAg8IAJAAQgJgFAAgPIAAgBIgGADIAABTQAAALgIADQgFACgTAAIgEAAIAAgDIgDgIIgEgHIAYABIAAgUIggASIgBgDQgEAOgGAHIgEAFgAhAAXQAAAfgLAOQAGADACAFQAJgMADgTIAFAJQAMgGAVgNIAAAcQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAIgSAAQADAFABAEQASABAEgCQAGgCAAgJIAAhQIg6AAgAAIA6QAAAJAEAEQAFADALABIAfAAQAKgBAFgFQADgGABgQQgFgBgFgEQAAAOgCAEQgCAFgGAAIgdAAQgGgBgCgBQgCgCAAgDIAAgbIAwAAIAAgKIgwAAIAAgVIgLAAgAAIgWQAAAKAEAEQAEAEAKAAIAwgBIgBgKQgEABgLAAIggAAQgHAAAAgIIAAgUIAvAAIAAgLIgvAAIAAgYIgLAAgAgEgXIAIgFQgEgOgSgXIgJAEQAGAGAGAMIglACQAMgNAMgUIgLgDQgJATgNAMQgEAGgEABIADAKQAEgBA0gEgAgqguIAUgBIgJgOgAg2AXIAAgeIAlAAIAAAhQgYANgOAGQABgKAAgMgAgyAmIAWgKIgVgPgAgzAHQAQAJAMAKIAFgHIgcgRgAgsAAIAXAMIAAgPIgcAAIAAADIABAAIABgCg");
	this.shape_4.setTransform(-127.4,0,5.044,5.044);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLBQIAAgEIgEgKIgDgGIAhAAIAAhHQggAuguAaIgDACIgCgEQgDgFgEgEIgFgEIAGgCQAUgLAUgTQAWgRAMgWIhIAAIAAgTIBXAAIAAgjIATAAIAAAjIAvAAIAAATIgvAAIAABVQABAOgLADQgGADgSAAgAgIBMIAIAAQAQAAAHgCQAHgDABgLIAAhZIAuAAIAAgLIguAAIAAgjIgNAAIAAAjIhWAAIAAALIBLAAQgMAYgWATQgXAWgXALQAEAEAFAGQAXgNAXgXQAWgVAOgZIAABVQAAAEgEAAIgZAAQADAIAAAEg");
	this.shape_5.setTransform(-215.1,-1.1,5.044,5.044);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-256.2,-42.1,512.5,84.3);


(lib.m_word = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiOG+QgHgIgGgEQATgUAKgWQAJgWADgYQACgYAAgWIAAhFQgQAUgTASQgTASgWAQIgKgOIgMgOQApgbAggoQAggoAVgtIh0AAIAAghICDAAIAMgeIAJgeIAjAIIgJAaIgJAaIDtAAIAAAhIj8AAIgNAbIgPAbIDhAAIAADtQAAAQgEAIQgFAJgLAEQgMAEgUABIgyABQgBgIgDgJIgHgRIAqABIAaAAQAGAAACgDQADgCAAgFIAAgxIjIAAQgEAagMAZQgLAZgVAUQgDgHgIgIgAhNEtIAAARIgBARIDDAAIAAgxIjCAAgAhNEAIDCAAIAAgvIjCAAgAgWgiIAAkRIgQAWIgRAUIgKgOIgMgMQAVgXASgcQASgdAOgeQALgfAJgcIAjAJIgOAkIgRAlIBWAAQgEgPgJgTQgIgSgKgQIAegNQAKARAJASQAJASAFAPIgdANIBgAAIAAAgIhVAAIAAA6IBLAAIAAAhIhLAAIAAA8IBLAAIAAAfIhLAAIAABAIBdAAIAAAhIjJAAIAAAhgAAKhkIBMAAIAAhAIhMAAgAAKjDIBMAAIAAg8IhMAAgAAKkgIBMAAIAAg6IhMAAgAjEhwIAAk0IB3AAIAAEQIhXAAIAAAkgAiki2IA3AAIAAjMIg3AAg");
	this.shape.setTransform(-32,-24);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-53.1,-70.1,42.3,92.2);


(lib.m_point2 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAg");
	this.shape.setTransform(33.5,-139,7.104,7.104,0,0,0,-5.5,-14.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAg");
	this.shape_1.setTransform(57.7,-26.6,7.104,7.104,0,0,0,-5.5,-14.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgBADIgBgDQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAQABgCACAEQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCAAIgBAAg");
	this.shape_2.setTransform(-94.9,81.7,7.104,7.104);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAADQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAQABgBAAAAQADgBACADQgBADgDAAIAAAAg");
	this.shape_3.setTransform(-82.9,-113.4,7.104,7.104);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAAAHQgBgGABgBIgBgGQABAEAAACQACAAAAAGIgCABIAAAAg");
	this.shape_4.setTransform(-78.6,100.8,7.104,7.104);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAAABQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAAAAAAAQABgCACACQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAIAAgBg");
	this.shape_5.setTransform(-72.9,135,7.104,7.104);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAAAAIABAAQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_6.setTransform(-67.8,138.6,7.104,7.104);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAAAAIACAAQABABgDAAQAAAAgBAAQAAgBAAAAQAAAAAAAAQABAAAAAAg");
	this.shape_7.setTransform(-66.4,-106,7.104,7.104);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAAAQgBAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAgBAAQAAABAAAAQAAAAgBAAIAAAAIAAgBg");
	this.shape_8.setTransform(-64.7,-118,7.104,7.104);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBACQgBgBAAAAQAAgBABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABAAQAAAAAAABQgBAAAAAAQAAABgBAAIgCAAg");
	this.shape_9.setTransform(-60,-138.1,7.104,7.104);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAABQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAAAg");
	this.shape_10.setTransform(-41.4,-121.2,7.104,7.104);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBABgBAAIAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAg");
	this.shape_11.setTransform(-33.4,-105.9,7.104,7.104);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgBAEQgBgEACgDIABgBQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABADgDAFIAAAAIgBgBg");
	this.shape_12.setTransform(-30.6,96.4,7.103,7.103,-45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgEAAIACgDQABgBAEABIACADQABACgGADQgFgBABgEg");
	this.shape_13.setTransform(27.2,-62.4,7.104,7.104);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAAACQgDgCADgCQAAAAAAAAQAAAAAAABQABAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgCACIAAgBg");
	this.shape_14.setTransform(14.5,-81.4,7.104,7.104);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgCABQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAABgBQABgCACACQABACgDABIgBABIgCgCg");
	this.shape_15.setTransform(20.8,-95.2,7.104,7.104);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_16.setTransform(61,-2.9,7.104,7.104);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAAABg");
	this.shape_17.setTransform(72.9,18.2,7.104,7.104);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBABQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAgBAAIAAAAIgBAAg");
	this.shape_18.setTransform(76.6,17.3,7.104,7.104);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAAABQgBAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQAAgBAAABQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAABIgBAAIAAgBg");
	this.shape_19.setTransform(76.8,11.2,7.104,7.104);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgCADQgCgBAAgEQADgCABAAQAEABAAADQABABgDACIgCACIgCgCg");
	this.shape_20.setTransform(80,36.2,7.104,7.104);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAg");
	this.shape_21.setTransform(57.2,-25.7,7.104,7.104,0,0,0,-5.5,-14.5);

	this.addChild(this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-97.6,-139.8,195.8,279.7);


(lib.m_point = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgBADIgBgDQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAQABgCACAEQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgCAAIgBAAg");
	this.shape.setTransform(-10.6,9.1,0.793,0.793);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAADQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAQABgBAAAAQADgBACADQgBADgDAAIAAAAg");
	this.shape_1.setTransform(-9.3,-12.7,0.793,0.793);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAAHQgBgGABgBIgBgGQABAEAAACQACAAAAAGIgCABIAAAAg");
	this.shape_2.setTransform(-8.8,11.3,0.793,0.793);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAABQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAAAAAAAQABgCACACQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAIAAgBg");
	this.shape_3.setTransform(-8.1,15.1,0.793,0.793);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAAAAIABAAQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_4.setTransform(-7.6,15.5,0.793,0.793);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAAAAIACAAQABABgDAAQAAAAgBAAQAAgBAAAAQAAAAAAAAQABAAAAAAg");
	this.shape_5.setTransform(-7.4,-11.8,0.793,0.793);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAAAAQgBAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAgBAAQAAABAAAAQAAAAgBAAIAAAAIAAgBg");
	this.shape_6.setTransform(-7.2,-13.2,0.793,0.793);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBACQgBgBAAAAQAAgBABAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQABAAAAAAQAAAAABAAQAAAAAAABQgBAAAAAAQAAABgBAAIgCAAg");
	this.shape_7.setTransform(-6.7,-15.4,0.793,0.793);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAABQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAAAg");
	this.shape_8.setTransform(-4.6,-13.5,0.793,0.793);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBABgBAAIAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAg");
	this.shape_9.setTransform(-3.7,-11.8,0.793,0.793);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBAEQgBgEACgDIABgBQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABADgDAFIAAAAIgBgBg");
	this.shape_10.setTransform(-4.2,10.3,0.793,0.793);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgEAAIACgDQABgBAEABIACADQABACgGADQgFgBABgEg");
	this.shape_11.setTransform(-0.4,-9,0.793,0.793);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAACQgDgCADgCQAAAAAAAAQAAAAAAABQABAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgCACIAAgBg");
	this.shape_12.setTransform(1.6,-9.1,0.793,0.793);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgCABQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAABgBQABgCACACQABACgDABIgBABIgCgCg");
	this.shape_13.setTransform(2.3,-10.6,0.793,0.793);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_14.setTransform(6.8,-0.3,0.793,0.793);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAAABg");
	this.shape_15.setTransform(8.1,2,0.793,0.793);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgBABQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAgBAAIAAAAIgBAAg");
	this.shape_16.setTransform(8.6,1.9,0.793,0.793);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAAABQgBAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAABQAAgBAAABQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAABIgBAAIAAgBg");
	this.shape_17.setTransform(8.6,1.2,0.793,0.793);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgCADQgCgBAAgEQADgCABAAQAEABAAADQABABgDACIgCACIgCgCg");
	this.shape_18.setTransform(8.9,4,0.793,0.793);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAg");
	this.shape_19.setTransform(10.7,8.6,0.793,0.793);

	this.addChild(this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.9,-15.6,21.8,31.2);


(lib.m_p8 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F66F49").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQABABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgBABIgBgCg");
	this.shape.setTransform(-56.9,-44.7,4.706,5.321,30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F66F49").s().p("AgBADQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAIgCAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAABIgBAAg");
	this.shape_1.setTransform(-70.9,-13.2,4.706,5.321,30);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F66F49").s().p("AAAABIAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAgBABIAAAAg");
	this.shape_2.setTransform(-61.2,-28.8,4.706,5.321,30);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F66F49").s().p("AgBAAIABgCQAAAAAAAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQAAABgBAAIgBABQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAg");
	this.shape_3.setTransform(-63.5,-15.8,4.706,5.321,30);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F66F49").s().p("AAAABQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAAg");
	this.shape_4.setTransform(-35,-58.8,4.706,5.321,30);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F66F49").s().p("AgBAAQABAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQgBAAAAABQAAAAgBAAIAAABQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAgBAAg");
	this.shape_5.setTransform(-31.2,-39.3,4.706,5.321,30);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F66F49").s().p("AgBACIAAAAIAAgDQAAgBABAAQAAAAAAAAQAAAAAAABQAAAAABABQAAAAABAAQAAAAAAAAQAAABAAAAQgBABAAAAIgBABIgBgBg");
	this.shape_6.setTransform(-4.9,-70,4.706,5.321,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_7.setTransform(-22.9,-40.8,4.706,5.321,30);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAABIAAgBg");
	this.shape_8.setTransform(-14,-49.1,4.706,5.321,30);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F66F49").s().p("AAAABQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABIgBAAIAAAAg");
	this.shape_9.setTransform(13.4,33.4,4.706,5.321,30);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgBgBg");
	this.shape_10.setTransform(10,-65.6,4.706,5.321,30);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F66F49").s().p("AAAAAIABAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAABAAAAIAAgBg");
	this.shape_11.setTransform(30.1,7.7,4.706,5.321,30);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F66F49").s().p("AAAAAIAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAgBg");
	this.shape_12.setTransform(23.3,-0.1,4.706,5.321,30);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F66F49").s().p("AAAAAIABAAIAAABQgBAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_13.setTransform(-45.9,50.7,4.706,5.321,30);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F66F49").s().p("AgBAAQgBAAAAAAQAAAAAAAAQABAAAAAAQAAgBABAAQAAAAAAAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAAAQgBABAAAAQgBABAAAAIgBAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBg");
	this.shape_14.setTransform(5.2,17.4,4.706,5.321,30);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F66F49").s().p("AgFADIAAAAIAAgDQAAAAAAgBQgBAAABgBQAAAAAAgBQAAAAAAAAQABgBAEgDQADgBADAFQABADgCADQgCADgDABIgBABg");
	this.shape_15.setTransform(-25.5,43.1,4.706,5.321,30);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F66F49").s().p("AAAABIAAgBIABAAQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIAAAAg");
	this.shape_16.setTransform(18.3,-27.5,4.706,5.321,30);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F66F49").s().p("AAAABQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABgBAAIAAAAIAAAAg");
	this.shape_17.setTransform(-6.2,23.9,4.706,5.321,30);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAIgBABIAAgBg");
	this.shape_18.setTransform(-8.1,29.3,4.706,5.321,30);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAIgBABIAAgBg");
	this.shape_19.setTransform(-23,58,4.706,5.321,30);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F66F49").s().p("AAAAAIAAAAIABAAIAAABIgBgBg");
	this.shape_20.setTransform(19.1,19.7,4.706,5.321,30);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F66F49").s().p("AAAABQgBgBAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgBAAIAAgBg");
	this.shape_21.setTransform(42.7,-10.7,4.706,5.321,30);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAIAAABQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAg");
	this.shape_22.setTransform(5.6,55.5,4.706,5.321,30);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F66F49").s().p("AAAAAIABAAQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_23.setTransform(9.1,50.6,4.706,5.321,30);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F66F49").s().p("AAAABQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAAAg");
	this.shape_24.setTransform(64.9,-37.1,4.706,5.321,30);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F66F49").s().p("AAAABIAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAABIAAAAg");
	this.shape_25.setTransform(44.1,8.7,4.706,5.321,30);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F66F49").s().p("AgCADIACgFQAAgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQABACgCACQAAAAAAABQgBAAAAABQAAAAAAAAQAAAAAAAAIgCgBg");
	this.shape_26.setTransform(-46.6,-26.4,4.706,5.321,30);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F66F49").s().p("AgCABQgBgCADgBQAAAAAAAAQAAAAABAAQAAAAABABQAAAAABABQAAAAgCADIgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAgBgBAAg");
	this.shape_27.setTransform(58,10.7,4.706,5.321,30);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_28.setTransform(47.2,32.3,4.706,5.321,30);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F66F49").s().p("AAAAAIABAAQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_29.setTransform(53.2,22.2,4.706,5.321,30);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIAAAAg");
	this.shape_30.setTransform(62.1,19.4,4.706,5.321,30);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAABIAAgBg");
	this.shape_31.setTransform(48.9,44.4,4.706,5.321,30);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F66F49").s().p("AAAAAIABAAIAAAAIgBABQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_32.setTransform(60.1,29.1,4.706,5.321,30);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F66F49").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAg");
	this.shape_33.setTransform(31.7,80.9,4.706,5.321,30);

	this.addChild(this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.5,-71.9,137.9,153.3);


(lib.m_p6 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAABQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABIgBAAIAAAAg");
	this.shape.setTransform(-49.2,-69.9,6.192,6.192);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAACIgCgCQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAAAAAQAAAAABAAQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQAAABgBAAIgCABIAAgBg");
	this.shape_1.setTransform(-41.5,5.8,6.192,6.192);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAABQAAAAgBAAQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIgCABIAAAAIAAAAg");
	this.shape_2.setTransform(-34.8,83.2,6.192,6.192);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIAAAAg");
	this.shape_3.setTransform(-22.9,-62.2,6.192,6.192);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAJAGQgOgFgEgCIgBgDQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAQABgBAFADQADABACACQAIADABACQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAAAIgCAAg");
	this.shape_4.setTransform(-1.4,31.9,6.192,6.192);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAAAAIABAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_5.setTransform(16,-36.4,6.192,6.192);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_6.setTransform(16.9,3.4,6.192,6.192);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAFAEIgGAAIAAgBQgFABgCgEQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAGgBAIAHQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAgBABIgBAAIgCAAg");
	this.shape_7.setTransform(15.2,62.2,6.192,6.192);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAgBAAIAAABIAAgBg");
	this.shape_8.setTransform(20.8,20.2,6.192,6.192);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQgBAAgBABIAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAAAg");
	this.shape_9.setTransform(24.6,-82.8,6.192,6.192);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgCAAQACgCADADIAAABQgEgBgBgBg");
	this.shape_10.setTransform(25.1,-52,6.192,6.192);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgSAFQgDABgDgCQgBgCAFgCIAVgDIAQgCIAFAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIABAAQgGADgKAAIgOABIgHABIgDADIgDABIgBgBg");
	this.shape_11.setTransform(13.9,76.4,6.192,6.192);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAAEQgEgBgDgDQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABABQAEACAJACIAAACIgJAAg");
	this.shape_12.setTransform(24.3,79.9,6.192,6.192);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAEABIgHABIgDgCQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQACgBAFABIAFABQABAAAAAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBg");
	this.shape_13.setTransform(26.3,18.2,6.192,6.192);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AABADQgEgDgBgBQAAgBABAAQAAAAAAAAQAAAAABAAQAAAAABAAIABAAIAFADQAAABAAAAQAAAAAAAAQAAAAgBABQAAAAAAAAIgCAAIgBAAg");
	this.shape_14.setTransform(36.1,-30.4,6.192,6.192);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgJAAIAAgCIAGAAQADABABgBIAFACIAEAAIgBADIgJAAIgJgDg");
	this.shape_15.setTransform(41,48.5,6.192,6.192);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDAAQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAABAAIABABQADABABACQABABgFAAQgCgCgBgBg");
	this.shape_16.setTransform(47.2,60.2,6.192,6.192);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgBAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAQAAAAAAABIADABQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgCgCg");
	this.shape_17.setTransform(-5.1,49.6,6.192,6.192);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBAAIABgBQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAQACACgEAAQgDAAACgCg");
	this.shape_18.setTransform(-43,68.3,6.192,6.192);

	this.addChild(this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-50.1,-84.1,100.3,168.4);


(lib.m_p4 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDABIAAgEIAAAAQABAAAAgBQAAAAABAAQABgBAAAAQAAAAAAAAQABABAAAAQABAAAAAAQABABAAAAQABABAAAAQABAGgEABIgBABQAAAAgDgFg");
	this.shape.setTransform(-2.6,2.1,8.177,8.177);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAABQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAAAg");
	this.shape_1.setTransform(8.4,-24,8.177,8.177);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgGAFQABgFADAAQACgDABABIACgCIAEgCQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgCACQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCADQgBABgEADg");
	this.shape_2.setTransform(11.6,8,8.177,8.177);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAQAAABAAAAQgBABgBAAIAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAg");
	this.shape_3.setTransform(17.6,-6.4,8.177,8.177);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQAGIAIACIAHgGQACgEAIgEIACgGQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQABABAAAAQAAAAAAABQABAAgBABQAAABAAAAQgBADgGAAIgGAGIAAAAIgIAJIABACQAAAAABAAQAAAAAAAAQABAAABgBQAAAAABgBQAFgFACAAQgFAGgCACIgCACQgIgGgGgCg");
	this.shape_4.setTransform(-6,13.7,8.177,8.177);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.9,-25.4,39.8,50.8);


(lib.m_p3 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAAHQgBgGABgBIgBgGQABAEAAACQACAAAAAGIgCABIAAAAg");
	this.shape.setTransform(-21.9,22.2,5.445,5.445,-30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgDADQgCgDACgCQADgDABACQAEAAAAADQAAACgCADIgCAAIgEgCg");
	this.shape_1.setTransform(-4.4,-8.8,5.445,5.445,-30);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABQAAACgBABg");
	this.shape_2.setTransform(21.2,-7.1,5.445,5.445,-30);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAADIgBgDIAAgCQADAAAAACQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgBABIAAAAg");
	this.shape_3.setTransform(10.3,-24.2,5.445,5.445,-30);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgBACQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAAAAAIADABQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAABIgBAAIgBAAg");
	this.shape_4.setTransform(23.5,-11.4,5.445,5.445,-30);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgCAFIAAgCIgBgDIAAgBIABgCQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAABAAQAAABAAAAQABAAAAAAQACAFgBABQgCAEgCAAIgCgBg");
	this.shape_5.setTransform(20.7,-15.9,5.445,5.445,-30);

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-25,-25.6,50.1,51.3);


(lib.m_p2 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgBABQAAgBgBAAQAAAAAAAAQAAAAABAAQAAgBABAAQAAAAAAAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABgBAAQAAABgBAAIgBAAQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAg");
	this.shape.setTransform(-20.2,10.7,6.24,6.24,-30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGACQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAAAABAAIACAAQABgBABgBQABAAABAAQAAAAAAAAQABAAAAABIAAAAIADAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAIAFABQAAADgEAAIgGAAQgEAAgCgBg");
	this.shape_1.setTransform(4.1,1,6.24,6.24,-30);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIgBABg");
	this.shape_2.setTransform(5.9,-8.9,6.24,6.24,-30);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBABQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAgBAAIAAAAIgBAAg");
	this.shape_3.setTransform(8.3,-11.3,6.24,6.24,-30);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgBADQgCgBAAgEQACgCABAAQADABABADQABABgCACIgDACIgBgCg");
	this.shape_4.setTransform(19.2,1.6,6.24,6.24,-30);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.3,-12.6,44.7,25.2);


(lib.m_p1 = function() {
	this.initialize();

	// flash0.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA4BbQgIgDgEgIQgIgCgEgEQgGgEgEgIQgDgIgCgIIgHAAQgBACgJACQAAABgEgEQAAAAAAABQAAAAAAAAQAAAAAAABQgBAAAAAAQgJgIgNAAQgPAAgIAMIgbgSIALgSQgFgFgBgHQgCgNAJgXQgPgMgDgGQgBgDAAgJIAAgBQgCgHAAgGIABgIQAAgDAFgBIABAAIABAAIABAAIABgBIAJgFIAAAAIABAAIACAAIABgBIAOAAIABABIADAAIABAAIACAAIABABIADAAIAAAAIABAAIABABIABAAIABABIABAAIABAAIACAAIAAABIABAAIABAAIAIADQAOAGAGABQAGgCAIACIAAACIAJAEIAAABIAAABIABAAIAAABIAAAEQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAAAAAQgDAHgGADQABABgFADIgCgBIgBAAIAAgBIAAAAIAAAAIgBAAIAAAAIgBgBIAAAAIAAAAIgBAAIAAgBIgBAAIgBAAIAAgGIgBgBQgFABgCgDQAAgBgNgBIgEAAIAFACIABABIABAAIABAAIABABIACABIAAAAIACACIAAABIABAAIAAABIAAABIACACIAAAAIABAAIAAABIAAAAIAAAAIABAAIAAABIAAAAIAAABIABAAIAAABIABAAIAAABIAAABIAAABIABAAIAAABIAIAIIAEgDIAAAAIABAAIABAAIACgBIABAAIABgBIAHgCIAEgIQAFgHACgBQACgBAIAAQAIABAEACQALAFABAIQAAgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABIgBAAIABAKIAAAAIgBABIAAAAIgBAAQACAGgBACQAAAAAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIAAACIgCABIgDgEIgDgCQgBAAAAAAQAAABgBAAQAAABAAABQAAAAgBABQAFABADADQAAAAABABQAAAAAAAAQAAABAAAAQgBAAAAABIAAAGIAAABQAAAEgOgFIAAABIgDAEIAAAAIgEAHQAHADAEAKQADAIgBAFQAGADAGAIIAAABIABAAIAAAAIAAABIAAAAIABABIAAABIAAAAIAAABIABABIAAAAIACAIIAAABIABABIAEgCIgBgGQgEgBgCgDIAAgCQAAAAAAAAQAAgBABAAQAAAAABgBQAAAAABgBIADgBIAAgBQgBgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQgBAAABgFQABgDAKAAQAHAAACACIAAAAIABAHQADAIgDAJIgDAJIgBANIgBAAIgCAJIgBABIAAABIgBAAIAAABIAAAAIAAABIgBACIAAAAIgCACIAAABIgDABIAAAAIgBABIAAAAIgBABIAAAAIgBAAQgGAAgGgDgAA2gkIAAgBIgCgCIgCgBg");
	this.shape.setTransform(79.8,-0.2,9.656,9.656);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgyCBIgBAAIgDgEQAAgFgCgBIgDgEIgCgBIgFgCQgBABAAgBQAAAAgBAAQAAgBAAgBQgBAAAAgCIAAgBIgCgBQgCgBABgIIgBgBIgCACIAAAEQAAAAAAABQABAAAAAAQAAABAAAAQgBABAAAAIABABQACABgBAEQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgCACQgCghgCgKQgLg4gEgZQgGgvAIgmQACgKgCgKIADACQAAgBAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAEABQAFABACgCIACgCIgBgCQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAABgBIAAgDIAAAAQABgDAEgBQAAABAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIgDAGIAAAAIAAACQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIACACIABAAIABABIAFAAIABgBQgBAAABAAQAAAAAAAAQAAAAABAAQABgBABAAIACgCQAAAAAAgBQABAAAAAAQAAgBAAAAQAAAAAAgBQgEgDAAgCIAAgDQgBAAAAAAQAAAAAAAAQAAgBAAAAQAAgBAAgBIAAgCQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAQACgDAEAFQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQACAEADAAQABAEgEAFIgBAEQAAABAAABQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAIAFACQADABACAAIAEgEQAAAAAAAAQAAgBAAAAQABgBAAAAQABAAAAgBQAFgFAHgFIACgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQgBAAAAABQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAIgEABIgGAGIgBABIgEAFIgCACIgDADIAAABQAAABABAAQAAAAABgBQAAAAABAAQAAAAABgBQAHgGADABQgFAFgFACQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgBACIABACIABADIAAgBIAAAIQAAABABAAQAAAAABAAQAAAAABAAQAAAAABAAQABgFAHgCIgBAAIAHAAQgHAYAMAVQAKAWAcABIAHAFQAKAGALABIAIABIAIAAIAHACIAAAAIgBADIgCACIAAAAQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAAAABQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIgEABIAAACIAAAGQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAABQAAAAABAAQAAABAAAAQABABAAAAQAAABAAABQAAAAABABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAABABIABAEQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIABAEQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAABIABAFIACAEQACACAEAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAgBAAIgEACIAAAAIgBACIABAEIADADIADACQAEAAAEAFQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgDgBIgHgHQgEgCgDAAIAAAAIgBgBQgBABAAAAQgBAAAAABQAAAAAAABQAAAAAAAAIgDACIgBAEIgBAFIgCAFQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIABACIgCgBQgBAAgBgHIgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAIgDgDIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAABAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQAAABgBAAIAAAAIgKACIAAAAQgGABgLgDIAAAAQgEAAgBgCIgBAAIgFgDQgCAAgDgDIgIgDQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAAAAABIAAAAIAEACQAFABABADIAFABQADABABACQgBABAAABQAAABAAAAQAAABAAAAQgBAAAAAAIgBABQgFgCgCgDIgCgDIgFgDIgBAAIgDADIgBAEIABAIIgBAAIAAACIACADQAAABgBABQAAAAAAAAQAAABAAAAQgBAAAAAAIABAEQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAAAQgBADgCgBIgEACIgDADQgBAAAAABQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAABQgBAAAAABIgEgBIgCADQgDAFgDgBQgGABgBgCIgBAAQgBACgFgBIgDABIABABIgCAAIgFABIABABIgFACQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBgABaB0QgFgDgBgDIgCgEQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAIgEABQgGgCgCgDIgCgCIgBgCQAAAAABAAQABAAAAAAQABABAAAAQABAAAAAAIABABIANABIACAEIACACIADACIACACQAAACABAAQAAABAAABQAAAAAAABQgBAAAAAAIAAAAg");
	this.shape_1.setTransform(30.5,2.3,9.656,9.656);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.3,-124.6,231.1,253.7);


(lib.m_moter2 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F66F49").s().p("A1FRpIAJghIAJggQAFgUADgaQAEgVAAgPQAEg1gHg9IgEghQgCgUgEgUQgQhihMicQhvjlgOgjQg/icAGh7QAGicBuiPQAtg8Ayg2QhOgjhOgfQAKg3gIhYIgCgNQBdA8BlBPIAZARQCbiXCghGQBQgjAygFIAMmhIE0FYIA3gFQBGgCBLANQDxAoDICsIHyAAQhJAphJAuQiTBdgCAfQABAAAGAXIEdhsQCpg9ArALQArAKC5DgQBdBxBUBuIBHhgQBHhjAAgQQAAgLArASQAxAUAvAmQCMByAACoIgfgpQgngygqgdQiMhjiVCQQAAAWAIAcQDXAhAYAAQAXAAABCGQABCRgpBdQgOhUgshPQhWieiggDQgCgFAiB6IAxCvQgDAchXAoQhaAphHAAQAfguAYhAQAxiAgfhKQgTgogjglQgsgvgygPQiLgqiFDZQgLhKAIhMQAOiUBdhHQADgDBJAoQBRArAmAAQAQAEhBiRQhBiTgogbQgPgKjAAZQi1AXhJARIAeCAIhNAAQgcAoghAsQhABVgdAXQAIgJgIiaQgfAkgmAoQhKBPghAVQAFgIALiQIjOCgIAjjeIgsASIiVCsIgVj9IjjCBIgQkXQh/CqgCgIQgFgRAzjKIAzjGQhLA3hFBvQiKDeAfEWQAAAKBXhFQAsgjArgmIhFEmIC6iKIgYEUICuhuIAtC/ICqjbIAYEDIAkgXIBejAIAxC3IBAjrIA3DKIEPiOQgoAqgwAuQhfBcgjAXQggAegnAiQhRBFhXAvQkWCXkrhUQhcgZhCgBQhagBg/AqQgxAhgQBIQgKApgJBVQgUBehdBTIgeAbIgUAQQgNAJgKAAQgUAAAJgfgAh4mNIAHANQAKAOAOALQAqAkA7gNQA9gNA8gxQAfgZASgWgAoypnQAKArAPAmQAtB3BFAKQBEAKArgGQAWgDAIgFIkfjzg");
	this.shape.setTransform(-53,16.8,0.407,0.407,-30,0,0,-160.6,-1.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-63.8,-52.9,127.6,105.8);


(lib.m_moter = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Am9URIgRgWQgYhdARiJQAbiXAKhBQAMhRgNihQgFg3gQiDQgDgigGgmIgGgfQglBVgcBRQgHAjABAlQABA/AZATQAdAWgTgJQgVgKgFgHIgRgSQgOgQgEgSQgOAygGAeQABAiAGAeQAIAxAPAHQAJAEgBACQAAADgHgDQgTgGgKgWIgPgeQgNBKgCBIIABAAIAIAoQAMAqAWAIQAKAEAAADQAAACgJgCQgYgFgSgZQADArAIAhQAHAbAHALQANAXAWAOQAMAIAIACQgBAXgpAFIgpAAIgMAEQgLAOABAvQACAygOANQgIAHgdACQgUACg+hHQg4hAgQggQgJgPAWhVQAOg1AjhyQgXAyglAWQgNAHgDgCQgEgCANgHQApgWAmhvQgEAEgOAFQgNAGAJgHQAOgLAig7IABAAIAGgUQgMAOgnAOQgOAFgJABQgQACAfgRQA4gfAhhJIAMghQgTAEgVAUIgIAHIAFgMQALgaAZglIAXggQgWAVgmADQgNABgFgCQgEgCAMgCQAfgFBdh8IANgiQgKAKgKAEIgMAEQgHACgFgDQgGgEAOgCQANgCAUgYIAQgXIABAAIAmhjQgTAOgYgCQgHgBgDgBQgBgBAAAAQAAAAAAAAQABAAABAAQABAAACAAQATAEAigaIABAAIAIgVQgYAQgnACQhNAFBHgJQAjgDAhgmIAZglIAlhfIAXg7QgbgDgXgdIgIgMQABgCAUARQATAQARgJQAJgEAFgIIAAAAQAghXACglQADgpguh1QgqhqgSgTQgMgNACgFQAAgBANgNQALgMAjgWQAkgWAIAAQAWAAAigGQAygKAHgQQAHgQAUgdIASgaQhDi9gGgoQgCgVAPgmIAPghQBCh6BXhRQAsgpAfgQQA6goAWAUQATAUgxAoQhcBIgcBuQgXBcAbBGQAUAzAgAEQAUACAygMQESglC5CnQBcBTAlBbQArAAASgHQA1gTAHhCQALhngVhTQgahMgHgbQgLgoATgHQATgGAYAgQBABYAQCaQALBpgLA8QgDAVgOAiQgSAvgWAaQgUAYgfASIgdAOQgGAEgGAHQgJALgCALQgDAXAEAgQAEAcAEAFQAFAGAdAQQAcAQARAGQASAGACANQACANgRALQgyAhgpAqQgvAxgRApQgFAOAJAeQAHAbgEAFQgKALhDAoQAZAWAkA5IADAAIAIAFQAJADAKgKIAJgJIgDAHQgKASgQADQAQAYATAkIAQASQAUASATgBQAugBgyAEQgVABgOgHIAIAPIAGABQAUALAJgDQgJAJgSgLIgGgEIAdA9QASATAJAAQAIABgDACQgDACgDgBIgHgBQgFgBgGgFIAJATQATAZAUAXQAhAmANACQAvAHg2gEQgbgBgPgQIAQAXQARAaAIASQAFAKgEgEQgLgLgIgEIAEAKQAZAvAlAVQAYAMgNgBIgRgEQgMgEgLgGQAXAlAIAGQAIAGgLgEQgLgFgDgDQgIgHAaA1QAYAzAWAMQAtAYgtgTQgVgIgTgaQADAFAAAGQAEAQgBgBIgIgPQARB/gUBCQgMAog7AaQgjAQgnAGQgIACgFgJQgGgJAHgIQAYgcAGhDQAGhDgVAKQgbAMgKgIIgEgMQALgDAPgZIAUgjQAFgKAEgWIADgUIgCgOQgHASgPAHQgFACgBgBQgBgBAGgDQAKgFAFgWIACgVIABgBQgFgYgKghIgHASQgEALgJAEQgSAIASgLQAMgHgCg3IgRgsQgDANgMAMQgCAEgKAGQgKAGAOgNQARgPgLg1QghhMguhOIgng+QA6CHAgDMQAFAeAVDCQAEApgRBsQgOBSgUBdQgOA/gYgGQgJgCgHgLQgGgJAAgHQAAgYgPhPQgThjgWgzQgVgygPgEQgFgCgEADIgCAEQiZBZkQgSQhWgGhYgQIhGgPQgoAYgnBLQgnBLgNBPQgKA5gQAAIgEgBgAj5kWQAAANANArQANAuANAWIgDAEIAFDmQADAoALAJQAMAKgFg6QgIhRAIiJQAqAGAWAEQgDgNgCgUIgDgiQgCgRADgIIAEgEIBIgBQAFABgGALIADAeQAEAjAGATQgFAJgDAxQgCArABASQABAPAGAAQAHABAAgPQgBgNADgrIACgrIADACQBAARA+AUQAFgLAFgXIADgWQAAgEABgDQADgGAIAEQAlAPA7AEQADABAFgBQADABgGAJQgKANgNA6IBsApQABAAAAAAQABAAABAAQAAAAABAAQAAAAABAAQAFgBALgRQAKgRAIgUQAGgOAHgEQADgBACABIBGAQQAUAFACAFQAAABAAAAQAAABgBAAQAAABAAAAQgBABgBAAIgoBEQgGAOABAFIADADQAPAIANAKQAjAaAGgDQAFgDAFgnQALhMBFhEQAugsAfgMQAMgFABgDQABgFgQgHQgGgCgMgCIgFAAQgQgEgRAPQgNAMgSAeQgZAsgSgHQgvgOgMgBQgIAAACgHIADgGQAOgMAIgcIAFgaIAAgBIgRAAQgsgCgxgTQgFAIgMAeQgJAWgHADQgRAFgqgWQgugYAPgaQANgXACgbIhlg9QgIAGgJAMQgQAVgJAeQgGAUgLgBIgWgLIhXgsQgDAAgBgEQgDgGAHgQQAKgYADgfQAEgmgOgMIgFgDQg4gggzgWQgLgCgBAfQgBAhABAlIgFALQgOAKgqgHQgngHgFgNQACgQgBgKQgCgogCgRQgIgsgRgLIgcgFQgMAIgEAVQgGAjATA+QABADgFABQgJAEgXgDQgdgDgGgEQgKgGgIgZIgRgtQgLgdABgRIgVAGQgTAIgEAHQgDAEACACQArAbAqCFQAfBjAGA1QADAeAaAEIgBgBQgPhVgLgRQgIgNARgMQANgKAXgFQALgCAPgGIABAAQAJAAgBAOgAIAlqQgUAJgSAUQgRAUgGAVQgFAUAJAIQAKAIAUgJQAUgJARgUQASgUAGgVQAFgUgKgIQgEgEgHAAQgIAAgKAFgABKo9QgQAEgGAaQgFAaAHAiQAIAiAQAVQARAWAPgEQAQgDAGgbQAGgagIgiQgHgigRgVQgOgTgOAAIgEABg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-85.5,-129.8,171.1,259.7);


(lib.m_kn = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhxDlQgNgHgCgPQgDgPAIgPIAIgIQhIgygShVQgThUAthLQAwhPBZgWQBWgVBPAvQA3AhAWA3QAYA6gZA3QgFAMhahRIgBABIgBgDIgTgRIANAfIgRAbIgkhYQgxgZg4ARQg3AQgeAyQggA1AOA5QAPA8A0AgIAXgpIAdBIIA2AiQgiAAgfgLQgBAIgFAJQgIAOgPAEQgGACgFAAQgIAAgIgFg");
	this.shape.setTransform(-18.3,-11.6,0.433,0.433,75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmjE/QgWgOgWgHQBNkAChirQENkkGiBVQAGABgSAIQgfAPgRALQhSAxgcBHQkkAujEDSQh2CAg7CaQgTgWgbgQg");
	this.shape_1.setTransform(10,5.4,0.433,0.433,75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgYgbIAQgdIAhBWIgQAbg");
	this.shape_2.setTransform(-15.8,-10.2,0.433,0.433,75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWgXIAQgdIAdBOIgRAbg");
	this.shape_3.setTransform(-21.6,-11.8,0.433,0.433,75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWgVIAQgeIAdBLIgRAcg");
	this.shape_4.setTransform(-23.6,-12.3,0.433,0.433,75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYgaIAQgdIAhBTIgRAcg");
	this.shape_5.setTransform(-17.7,-10.7,0.433,0.433,75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXgYIAQgeIAfBRIgRAcg");
	this.shape_6.setTransform(-19.7,-11.3,0.433,0.433,75);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-29.2,-21,58.6,42.1);


(lib.m_fire = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ak8LBIE7m9IjiDhIkCkCIDYjYImyEzIoEh/IN8pfIE+BPQEJk1HJk/QDBiGCJhFQCPhIAbAbQAaAahHCQQhFCMiDC/QlAHQk2D9IBQFEIpfN8gAA9iTQgoACgbAdQgdAdgCAnQgCAnAaAYQAYAaAngCQAngCAdgdQAdgbADgnQACgngagaQgYgZgjAAIgGABgAErmbQgxADglAlQglAlgDAxQgCAyAhAhQAhAhAygCQAxgDAlglQAlglADgxQACgyghghQgfgfgtAAIgHAAgAIapxQgnACgdAdQgdAdgCAnQgCAnAaAaQAaAaAngCQAngCAdgdQAdgdADgnQACgngbgaQgXgZgjAAIgHABg");
	this.shape.setTransform(0,0,0.106,0.106,0,0,0,0.1,0.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13,-13,26,26);


(lib.m_Bat = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F66F49").s().p("AASCTQgNgXgSgBQgQgCgWAPQgBAAAAAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgOg2g0AQQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQgWg4hQABQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAABgBQBWgzBdAdQAAAAABAAQAAABAAAAQABAAAAABQgBAAAAABQgFAqAjAFQAeAEAPgXIAAgBIgBgCQgDgDgDABQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgEgJIAAAAQgFgCAAgDQAAgGgIAAIAAgBQAIgFAJAEIACgEIADgCIADgCIAFAAIAEABQAEgLAKAAIAAABQgFAFADAEQACADgCADIgBABIAEAKQAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQgDADAAADIABACIABABQAbAGAUgaQAVgaghgaQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBABAAQAshXBigXQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABQg5A4AYA3QAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgwAaAbAuIABABIgCABQgaAGgKAMQgNAOAHAaQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgygXQAEAQgKASQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQgTgHgJgOIgUA0IgBAAIgBAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.7,-14.7,45.5,29.6);


(lib.logo2 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiLCDQgPgMAAgSIAAjJQAAgTAPgLQAPgLAUADIBZANIAAAeQgjABgYAZQggAeABAsQACAqAcAcQAbAbAmgBIgBAZIhdAOIgHAAQgPAAgNgJgAAIB7IAAgZQAggIATgcQAUgcgBgiIAAgIIhcABIAAAVIBLgEQgDAagRAUQgSATgXADQgfAEgXgWQgYgVgBgjQgBggAXgYQAWgWAfACIAAAAQAiACAUAcIANgNQgWggglgGIAAgdIB9ASQALACAHAKQAIAKAAAOIAACKQAAANgHALQgIAKgLABIiBATg");
	this.shape.setTransform(3.2,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKCHIAAj3IhWAAIAAgXIDBAAIAAAXIhWAAIAAD3g");
	this.shape_1.setTransform(107.7,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhfCHIAAkOIAaAAICNDjIABAAIAAjjIAXAAIAAENIgaAAIiNjiIgBAAIAADjg");
	this.shape_2.setTransform(86.4,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKCHIAAkOIAVAAIAAEOg");
	this.shape_3.setTransform(71.9,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgxCAQgWgKgOgUQgOgSgIgbQgHgaAAgbQAAgZAHgbQAIgaAOgTQANgSAXgMQAWgMAbAAQAcAAAWAMQAXAMANASQAPAVAHAYQAHAaAAAaQAAAcgHAZQgHAZgPAUQgOAUgWAKQgWAMgcAAQgbAAgWgMgAgohrQgSAKgLARQgMARgFAVQgFAXAAATQAAAVAFAWQAFAVAMARQALARASAKQARAKAXAAQAYAAARgKQATgLAKgQQALgRAFgVQAGgTAAgYQAAgWgGgUQgFgVgLgRQgKgQgTgLQgRgKgYAAQgXAAgRAKg");
	this.shape_4.setTransform(56.7,-0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhZCHIAAkOIBqAAQAQABAOAFQANAFALAKQAKAKAEAOQAFAPAAASQAAASgFAOQgEAOgKALQgLAIgNAFQgNAFgRAAIhUAAIAAB1gAhDgCIBPAAQAYAAAQgOQAPgNAAgcQAAgcgPgOQgQgNgYAAIhPAAg");
	this.shape_5.setTransform(34.2,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AALCLQgtgCgigWQg0glAAhSQAAgkAWgkQAkg/BRAAQAtACAcAXQATAOAIAUIgqAMQgDgLgPgJQgSgKgYAAQglABgXAaQgWAaABAtQAAA9AmAZQAUANAZABQAeABAWgEIABgBIAAhMIgBgBIhTAAIAAgpICFAAIAACbQglAHgqAAIgfgBg");
	this.shape_6.setTransform(-105.3,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHCLQgtgBgegcQgPgPgIgUIgBgCIArgOQARAnArACQAaABAQgKQAOgJAAgQQABgRgXgLIgzgSQhNgZgBg6QAAgTAKgQQAPgYAegLQAPgFAZAAQAuAAAaAXQANAMALAYIgpAMQgCgMgNgLQgQgNgWABQgZAAgNAMQgLAJABAMQAAAbAqAOIBKAYQAWAKAKAVQAIAOgBAMQABBWhpAAIgJAAg");
	this.shape_7.setTransform(-54.2,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABRCHIhQjCIgBAAIhRDCIg4AAIB0kOIArAAIB0EOg");
	this.shape_8.setTransform(-78,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA9CHIAAhxIh5AAIAABxIg1AAIAAkOIA1AAIAAB0IB5AAIAAh0IA1AAIAAEOg");
	this.shape_9.setTransform(-30.1,0);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-117.4,-14.2,234.9,28.5);


(lib.g_line_2 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2,1).p("ABQAAIAFAAAhUAAIAFAAAAnAAIAFAAAgCAAIADAAAgrAAIAFAA");
	this.shape.setTransform(154.2,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(144.6,-1,19.2,2);


(lib.g_line = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,2,1).p("AGIAAIAFAAAFeAAIAFAAAE0AAIAFAAAEKAAIAFAAADhAAIAFAAAA6AAIAFAAABkAAIAFAAACOAAIAFAAAC4AAIAFAAAg+AAIAFAAAgVAAIAFAAAARAAIAFAAAiSAAIAFAAAhpAAIAFAAAmMAAIAFAAAjlAAIAFAAAkOAAIAFAAAk5AAIAFAAAliAAIAFAAAi8AAIAFAA");
	this.shape.setTransform(123,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,2,1).p("ADhAAIAFAAAEKAAIAFAAAE0AAIAFAAAFeAAIAFAAAGIAAIAFAAAA6AAIAFAAAARAAIAFAAAC4AAIAFAAACOAAIAFAAABkAAIAFAAAi8AAIAFAAAgVAAIAFAAAg+AAIAFAAAhpAAIAFAAAiSAAIAFAAAmMAAIAFAAAliAAIAFAAAk5AAIAFAAAkOAAIAFAAAjlAAIAFAA");
	this.shape_1.setTransform(39.7,0);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-1,164.8,2);


(lib.g_Gash = function() {
	this.initialize();

	// flash0.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AALCLQgtgCgigWQg0glAAhSQAAgkAWgkQAkg/BRAAQAtACAcAXQATAOAIAUIgqAMQgDgLgPgJQgSgKgYAAQglABgXAaQgWAaABAtQAAA9AmAZQAUANAZABQAeABAWgEIABgBIAAhMIgBgBIhTAAIAAgpICFAAIAACbQglAHgqAAIgfgBg");
	this.shape.setTransform(-192,-0.3,5.141,5.141);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHCLQgtgBgegcQgPgPgIgUIgBgCIArgOQARAnArACQAaABAQgKQAOgJAAgQQABgRgXgLIgzgSQhNgZgBg6QAAgTAKgQQAPgYAegLQAPgFAZAAQAuAAAaAXQANAMALAYIgpAMQgCgMgNgLQgQgNgWABQgZAAgNAMQgLAJABAMQAAAbAqAOIBKAYQAWAKAKAVQAIAOgBAMQABBWhpAAIgJAAg");
	this.shape_1.setTransform(70.4,-0.2,5.141,5.141);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABRCHIhQjCIgBAAIhRDCIg4AAIB0kNIArAAIB0ENg");
	this.shape_2.setTransform(-51.5,-1.4,5.141,5.141);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA9CHIAAhyIh5AAIAAByIg1AAIAAkNIA1AAIAABzIB5AAIAAhzIA1AAIAAENg");
	this.shape_3.setTransform(194.6,-1.4,5.141,5.141);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-254.5,-72.6,508.2,144.7);


(lib._5 = function() {
	this.initialize();

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjtBqIgGgGQARgGAJgIQAKgHAFgIQAEgIACgIIABgOIAAgPIARAAIAAAPQAAAJgCAJQgCAKgFAJQgFAKgLAJQgLAJgRAHIgGgHgAFWBoIgEgIIAUAAIAQAAIAKAAQAEgBABgBQACgCAAgDIAAhFIhnAAIAAgRIBnAAIAAhSIgqAEIgoABIgCgHIgCgIIAtgCIAvgDIAsgGQAUgDAPgEIAIAPQgPADgUAEIgpAFIAABTIBjAAIAAARIhjAAIAABFQAAAJgDAFQgDAEgGADQgHABgMABIggABIgDgJgAn+BjIAMgQQAGgHAFgFQAGgLAFgPQAFgOADgOIgfAAIAMgYIAMgdIggAAIAAgPIA2AAIgMAdIgMAZIAQAAIACgBIAIADIgIAiQgGAQgGAOIAJAGIAMAJQANAHARACQARACAXABIAigBIAigCIAfgCQgCADgBAFIgCAIIgSABIgZABIgbABIgZAAQgYAAgSgDQgRgDgNgIIgKgHIgIgFQgEgDgDAAQgDAAgDAFIgIALIgHAQgAAqBsIgHgEQAHgMAEgRQAEgQABgUQACgUAAgUIAPABIgBAQIgBARQAEANAGAKQAFAJAIAHIAAhcIgwAAIAAgOIAtAAIAAgfIgoAAIAAgQIAoAAIAAgeIAPAAIAAAeIAnAAIAAAQIgnAAIAAAfIAsAAIAAAMQARgLAKgPQAJgPADgXIgkAAIAAgPIBrAAIAAADIAAAFIgCAkQgCANgCAIQgBAHgDADQgDAEgDABIgIABIgLAAIgQAAIgBgHIgDgHIAPAAIAJABIAFgBQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAIADgIIACgQIACgbIgnAAQgEAcgMATQgMASgUALIgFgEIgHgGIgkAAIAAAjIAnAAIAAAPIgnAAIAAAzQALAEAPACQAPACATAAIANAAIAXAAIAaAAIAYAAIAPAAQgCADgCAEIgCAJIhfAAQgbAAgTgDQgTgEgOgKQgNgJgJgRQgCAOgEANQgDANgGAKIgGgEgAupBpIgFgFQASgHAMgKQALgKAGgNQAHgNACgRQADgSAAgTIgiAAIAAgPICMAAIAAAPIgrAAIAABeQgBAEACACQABABAEABIASAAQADgBACgCIACgJIABgWQACADAFABIAHADQAAARgCAJQgCAJgFADQgEAEgHAAIgWAAQgMAAgFgFQgEgFAAgNIAAheIgeAAQgBAWgDASQgDATgHAPQgHAPgMAMQgNALgUAHIgEgHgAh0BwIAAhWIAQAAIAABWgAqLBwIAAhIIhlAAIAAgPIBlAAIAAgPIARAAIAAAPIBlAAIAAAPIhlAAIAABIgAMoBvIAAiHIgLAPIgLAMIgFgGIgFgIQAMgNAKgPQALgQAJgSQAJgSAHgTIAPAEIgMAdQgGAOgHANIAAChgAOJBuIgIAAIgCgHIgDgHIAKAAIAIAAIAGAAQAEgBACgDQAFgFACgKQACgLgDgNQgLALgNAIQgOAJgOAIQgPAHgOAGIgFgHIgFgGQAQgEARgIQAQgHAPgLQAOgJAKgKIgDgIIgDgHQgKAIgMAIIgZAOIgYALIgFgGIgEgFQAMgEAOgGIAagOQAMgHAJgJIgFgGIgHgGQgNAJgOAIQgPAIgOAEIgEgFIgFgFQAKgDALgFIAWgLQAKgEAJgGIgqAAIAAgnIgGAHIgIAFIgFgFIgFgFQANgKALgLQALgMAIgMIAOgWIAPADIgEAHIgEAIIAuAAIADgBIAJAGQgEAIgFAHIgLAOIA2AAIAAA0IhIAAIgCACIgDACQAHAEAGAHQAGAHAEAIIAQgJIAQgJIANgHIALAJIgNAIIgPAIQAEAMAHAMQAGALAIAKQAJAJAJAGIgGAFIgFAHQgJgHgJgKQgIgKgHgNQgGgNgFgNIgFADIgGACQAFAOABANQABAOgDALQgCAKgGAHQgFAEgFABQgFACgHAAIgHAAgAOggUIAsAAIAAgbIgsAAgANmgUIArAAIAAgbIgrAAgANuhGIgJALIAvAAIAIgKIAIgMIguAAIgIALgAJcBpQgHgCgDgGQgCgEAAgJIAAgpIAQAAIAAApQAAAFADABQADABALAAIAyAAQAGAAADgCQADgCABgGQACgGAAgNIAHAFIAIACQgBAOgDAJQgCAIgGADQgGAEgLgBIg0AAIgFAAQgJAAgGgBgAo1BZIgagRIgbgPIAKgLIAbAOIAaARIAVAPIgKANQgIgIgNgIgAruBgIgGgHQAOgDAPgHQAPgGANgIQAMgIAJgJIAOAFQgKALgNAKQgNAJgPAIQgQAIgOAEIgFgHgAIWBcQAFgHAEgJIAIgRIAGgRIAOAFIgGASIgIASQgEAJgFAHgALbBOIgKgSIgKgSIAOgGIAKARIALARIAIAQIgPAHIgIgPgAm2BSIgFgFQAPgEAJgFQAKgGAFgIQAGgHACgJIgsAAIAAgLIBBAAIgDgHIgDgHIANgDIAFAIIAEAJIBCAAIAAALIhYAAIgCAEIgBAFIBGAAIAAACIgBAEQgCANgDAGQgDAIgEACIgGADIgHABIgLAAIgPgBIgBgFIgCgFIAOABIAKAAIAEAAIADgCIAEgGIAEgKIg7AAQgGAKgLAIQgMAHgRAFIgDgGgAvrBCIARgEIATgFIAAg+IgdAAIAAgPIAdAAIAAg4IggAAIAAgQIBRAAIAAAQIghAAIAAA4IAdAAIAAAPIgdAAIAAA6IASgFIASgFIACAPIgeAJIgeAIIgaAHgAKIA8IgMgNIgMgNIALgIIAMAMIAMANIAKAKIgMAKIgJgLgACcBEIAAhJIBeAAIAABJgACsA2IA+AAIAAgwIg+AAgAj+AsIgGgGQAOgFAOgGQAPgHANgIQAMgKAKgHIgzAAIAAhiICnAAIAABiIgyAAQAKAHANAJQAMAIAPAHQAOAGAPAEIgGAHIgFAIQgRgGgQgJQgQgIgOgLQgOgLgKgLIgcAAQgKAKgOALQgOAMgQAJQgQAJgRAFIgEgHgAiOgUIA7AAIAAgcIg7AAgAjZgUIA7AAIAAgcIg7AAgAiOg+IA7AAIAAgbIg7AAgAjZg+IA7AAIAAgbIg7AAgAJFAeIAAhDQgIAQgLAOQgKAMgMAJIgEgGIgGgEQAJgGAJgJQAJgLAIgMQAHgMAGgNIgrAAIAAgPIAuAAIAAgkIAQAAIAAAkIAnAAIAAAPIgnAAIAAAOIAJAHIANAJIALAIIAIAGIgJANIgJgIIgLgKIgMgJIAAA7gAKHAbIAAh9IBfAAIAAB9gAKXAOIA/AAIAAgXIg/AAgAKXgWIA/AAIAAgZIg/AAgAKXg8IA/AAIAAgYIg/AAgAm3ASIgEgEQAVgDAMgGQAMgEAEgIIglAAIAAAMIgOAAIAAgWIBFAAIgCgFIgDgGIgvAAIAAhEIAtAAIADgIIAEgHIARACIgFAHIgEAGIA8AAIAABEIg4AAIADAGIACAFIBFAAIAAAWIgPAAIAAgMIggAAIAAALIABAEIAEABIAXAAIAHAAIAHgBIABAGIAAAEIgGAAIgJABIgcAAQgJAAgCgEQgDgEAAgHIAAgLIgcAAQgFALgOAIQgOAHgYAEIgDgFgAmcglIBYAAIAAgKIhYAAgAmcg4IBYAAIAAgLIhYAAgAmchMIBYAAIAAgLIhYAAgAojAHIgBgGIgZAEIgPABIgIACIgDABIgCgGIgDgFQADgBAEgDIAIgKIAIgKIAMgRIgTADIgKACIgEABIgCgHIgCgGIAEgEIAFgHIAGgLIAJgRIAHgVIAOAEIgMAdIgOAYIAagDIAGgLIAGgMIAMAHQgKASgLASQgMARgNAPIAggEIgDgIIgDgIIALgEIAHAUIAFAQIgMAEIgBgFgAq0AEIgBgFIgeADIgPADIgGACIgBgHIgDgEQADgBAEgEIAIgJIAIgLIALgQIgRACIgIACIgEACIgCgHIgDgHQADAAACgDIAFgHIAGgKIAIgRQAEgKADgKIAOAFIgMAaQgHANgHALIAXgCIAGgMIAHgNIAMAHQgKATgMARQgMARgNAOIAhgDIgCgJIgDgJIAMgDIAEAOIADAOIACAKIgMADIgBgFgAqiAEIAAhcIAUAAIADgMIACgMIAQADIgEALIgEAKIAeAAIAABcgAqTgIIAiAAIAAgbIgiAAgAqTgvIAiAAIAAgbIgiAAgAFPgWIgJgTIgJgTIANgFQAGAIAEAKIAJATIAGARIgPAGIgFgRgAG4gLIAKgSIAKgUIAIgUIARAFIgKAVIgLAUIgKASgAnghNIgHgPIgGgNIANgFIAKAVIAJATIgOAFIgFgMgAuJhPIAAgPIBzAAIAAAPg");
	this.shape.setTransform(-12.1,-2.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-112.5,-14.2,200.9,22.7);


(lib._4 = function() {
	this.initialize();

	// flash0.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiLCDQgPgMAAgSIAAjJQAAgTAPgLQAPgLAUADIBZANIAAAeQgjABgYAZQggAeABAsQACAqAcAcQAbAbAmgBIgBAZIhdAOIgHAAQgPAAgNgJgAAIB7IAAgZQAggIATgcQAUgcgBgiIAAgIIhcABIAAAVIBLgEQgDAagRAUQgSATgXADQgfAEgXgWQgYgVgBgjQgBggAXgYQAWgWAfACIAAAAQAiACAUAcIANgNQgWggglgGIAAgdIB9ASQALACAHAKQAIAKAAAOIAACKQAAANgHALQgIAKgLABIiDAUg");
	this.shape.setTransform(0.1,1.2,13.896,13.896);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-216.3,-194.1,432.9,390.6);


(lib.mc_line = function() {
	this.initialize();

	// 圖層 1
	this.instance = new lib.g_line_2("synched",0);
	this.instance.setTransform(342.5,2.7);

	this.instance_1 = new lib.g_line("synched",0);
	this.instance_1.setTransform(321.8,2.7);

	this.instance_2 = new lib.g_line("synched",0);
	this.instance_2.setTransform(156,2.7);

	this.instance_3 = new lib.g_line("synched",0);
	this.instance_3.setTransform(-9.7,2.7);

	this.instance_4 = new lib.g_line("synched",0);
	this.instance_4.setTransform(-175.5,2.7);

	this.instance_5 = new lib.g_line("synched",0);
	this.instance_5.setTransform(-341.6,2.8);

	this.instance_6 = new lib.g_line("synched",0);
	this.instance_6.setTransform(-507.3,2.8);

	this.addChild(this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-508.3,1.7,1014.6,2.1);


(lib.m_p5 = function() {
	this.initialize();

	// 圖層 1
	this.instance = new lib.m_p1();
	this.instance.setTransform(-151.3,-2.1,0.958,0.971,0,0,0,-108.8,0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-110.6,-123.1,221.4,246.3);


// stage content:
(lib.gash = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_128 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(128).call(this.frame_128).wait(1));

	// 圖層 3
	this.instance = new lib.logo2();
	this.instance.setTransform(733.2,330.1,3.787,3.787);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(114).to({_off:false},0).to({y:283.3,alpha:1},4).wait(11));

	// 圖層 5
	this.instance_1 = new lib.mc_line();
	this.instance_1.setTransform(733.2,513.4,2.12,1);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(112).to({_off:false},0).to({scaleX:0.74,x:700},10,cjs.Ease.get(-1)).wait(7));

	// p
	this.instance_2 = new lib.m_fire();
	this.instance_2.setTransform(1165.2,304.4,0.761,0.761);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(20).to({_off:false},0).to({scaleX:1.18,scaleY:1.18,x:1196.6,y:264.5},16,cjs.Ease.get(1)).to({x:1199.6},66).wait(7).to({x:1196.6},0).to({scaleX:0.42,scaleY:0.42,x:859.5,y:238.2,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_3 = new lib.m_kn();
	this.instance_3.setTransform(1067.9,474.9,0.66,0.66);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(20).to({_off:false},0).to({scaleX:1.18,scaleY:1.18,rotation:15,x:1144.1,y:538.4},17,cjs.Ease.get(1)).to({x:1147.1},65).wait(7).to({x:1144.1},0).to({scaleX:0.42,scaleY:0.42,x:840.9,y:335.1,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_4 = new lib.m_Bat();
	this.instance_4.setTransform(1200.4,476,0.562,0.562);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(20).to({_off:false},0).to({scaleX:1.18,scaleY:1.18,x:1163.5,y:405.1},17,cjs.Ease.get(1)).to({x:1166.5},65).wait(7).to({x:1163.5},0).to({scaleX:0.42,scaleY:0.42,x:847.8,y:288,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_5 = new lib.m_p8();
	this.instance_5.setTransform(1015.3,393.8,0.331,0.331,9.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(16).to({_off:false},0).to({scaleX:1.62,scaleY:1.62,x:1061.6,y:407.1},20,cjs.Ease.get(1)).to({x:1064.6},66).wait(7).to({x:1061.6},0).to({scaleX:0.57,scaleY:0.57,x:811.7,y:288.7,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_6 = new lib.m_p6();
	this.instance_6.setTransform(864.6,419.7,0.361,0.361,151.8);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(20).to({_off:false},0).to({scaleX:1.29,scaleY:1.29,x:942.3,y:412.5},20,cjs.Ease.get(0.99)).to({x:945.3},62).wait(7).to({x:942.3},0).to({scaleX:0.46,scaleY:0.46,x:769.5,y:290.6,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_7 = new lib.m_point("synched",0);
	this.instance_7.setTransform(1174.2,376.4,1.184,1.184);
	this.instance_7._off = true;

	this.instance_8 = new lib.m_point2("synched",0);
	this.instance_8.setTransform(1174.2,376.4,1.184,1.184);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(18).to({_off:false},0).to({_off:true},18,cjs.Ease.get(1)).wait(93));
	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(18).to({_off:false},18,cjs.Ease.get(1)).to({x:1177.2},66).wait(7).to({x:1174.2},0).to({scaleX:0.42,scaleY:0.42,x:851.6,y:277.8,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_9 = new lib.m_p4();
	this.instance_9.setTransform(1184.5,424.6,0.594,0.594);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(18).to({_off:false},0).to({scaleX:1.17,scaleY:1.17,x:1216.5,y:402.4},18,cjs.Ease.get(0.96)).to({scaleX:1.18,scaleY:1.18,x:1217.4,y:401.8},2).to({x:1220.4},64).wait(7).to({x:1217.4},0).to({scaleX:0.42,scaleY:0.42,x:866.9,y:286.8,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_10 = new lib.m_p3();
	this.instance_10.setTransform(1090.8,460.4,0.778,0.778);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(18).to({_off:false},0).to({scaleX:1.17,scaleY:1.17,x:1127.7,y:503.3},18,cjs.Ease.get(1)).to({scaleX:1.18,scaleY:1.18,x:1129.3,y:505.1},3).to({x:1132.3},63).wait(7).to({x:1129.3},0).to({scaleX:0.42,scaleY:0.42,x:835.7,y:323.3,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_11 = new lib.m_p2();
	this.instance_11.setTransform(1173.2,307.6,0.157,0.157,0,0,0,-22.3,12.4);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(18).to({_off:false},0).to({scaleX:1.09,scaleY:1.09,x:1186.7,y:294.9},18,cjs.Ease.get(0.98)).to({regX:-22.4,regY:12.6,scaleX:1.18,scaleY:1.18,x:1188.1,y:293.5},5).to({x:1191.1},61).wait(7).to({x:1188.1},0).to({scaleX:0.42,scaleY:0.42,x:856.5,y:248.5,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// p
	this.instance_12 = new lib.m_moter();
	this.instance_12.setTransform(1102.6,295.9,0.035,0.035,0,0,0,-87,131.2);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({_off:false},0).to({regX:-85.7,regY:129.9,scaleX:0.42,scaleY:0.42,x:1102.5},20,cjs.Ease.get(1)).to({x:1105.5},63).wait(7).to({x:1102.5},0).to({regX:-85.8,regY:130,scaleX:0.15,scaleY:0.15,x:826.2,y:249.3,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// 小怪獸
	this.instance_13 = new lib.m_moter2();
	this.instance_13.setTransform(989.3,393.3,0.134,0.134,0,0,0,-64,0);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(17).to({_off:false},0).to({regX:-63.8,scaleX:1.18,scaleY:1.18,x:983.9},20,cjs.Ease.get(1)).to({x:986.9},65).wait(7).to({x:983.9},0).to({regX:-63.9,scaleX:0.42,scaleY:0.42,x:784.2,y:283.8,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// 潑漆
	this.instance_14 = new lib.m_p5();
	this.instance_14.setTransform(1024.5,383.9,0.123,0.643,0,0,0,-20,0);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(14).to({_off:false},0).to({scaleX:1.18,scaleY:1.18,x:1104.2,y:384},28,cjs.Ease.get(0.94)).to({x:1107.2},60).wait(7).to({regX:-20.3,scaleX:1.18,scaleY:1.18,x:1104.4,y:383.9},0).to({scaleX:0.42,scaleY:0.42,x:826.9,y:280.5,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// logo
	this.instance_15 = new lib._4();
	this.instance_15.setTransform(468.9,388.6,0.769,0.769);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({scaleX:0.91,scaleY:0.91,x:905.5,y:390.3,alpha:1},14,cjs.Ease.get(1)).wait(95).to({scaleX:0.32,scaleY:0.32,x:756.5,y:282.7,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// 唯有
	this.instance_16 = new lib.m_word("synched",0);
	this.instance_16.setTransform(740.9,376.8);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(7).to({_off:false},0).to({x:164.9,alpha:1},7,cjs.Ease.get(1)).wait(95).to({startPosition:0},0).to({x:274.7,y:312},10,cjs.Ease.get(-1)).wait(10));

	// 玩樂邊界
	this.instance_17 = new lib._5();
	this.instance_17.setTransform(836.8,242.2,1,1,0,0,0,34.5,-3.1);
	this.instance_17.alpha = 0;
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(7).to({_off:false},0).to({x:260.8,alpha:1},7,cjs.Ease.get(1)).wait(95).to({x:733.2,y:177.4},10,cjs.Ease.get(-1)).wait(10));

	// gash
	this.instance_18 = new lib.g_Gash();
	this.instance_18.setTransform(999.1,353.2,1,1,0,0,0,-0.4,-0.4);
	this.instance_18.alpha = 0;
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(7).to({_off:false},0).to({x:423.1,alpha:1},7,cjs.Ease.get(1)).wait(95).to({regX:-0.5,scaleX:0.79,scaleY:0.79,x:466.2,y:286.6,alpha:0},10,cjs.Ease.get(-1)).wait(10));

	// 即刻入場
	this.instance_19 = new lib.m_word2();
	this.instance_19.setTransform(967.3,493.9,1.118,1.118);
	this.instance_19.alpha = 0;
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(7).to({_off:false},0).to({x:391.3,alpha:1},7,cjs.Ease.get(1)).wait(95).to({x:700,y:411.1},10,cjs.Ease.get(-1)).wait(10));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1002.6,639.4,332.8,300.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;